import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="{inter.className}">
        <div className="max-w-screen-lg mx-auto">
          {/*   <header>
            <nav>
              <div className="">
                <ul className="flex items-center justify-center p-4 bg-black text-white space-x-16 font-bold mb-2">
                  <li className="font-bold text-3xl">
                    <a href="#">Delta Executor</a>
                  </li>
                  <li className="mt-2">
                    <a href="#">Delta Executor Key</a>
                  </li>
                  <li className="mt-2">
                    <a href="#">Delta Executor PC</a>
                  </li>
                  <li className="mt-2">
                    <a href="#">Discord Server</a>
                  </li>
                  <li className="mt-2">
                    <a href="#">Server Status</a>
                  </li>
                </ul>
              </div>
            </nav>
          </header> */}

          <header className="mb-2">
            <nav className="bg-white border-gray-200 px-4 lg:px-6 py-2.5">
              <div className="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
                <a href="/" className="flex items-center">
                  <img
                    src="/Image/Delta-Executor-official-logo.webp"
                    className="mr-3 h-6 sm:h-9"
                    alt="Flowbite Logo"
                  />
                  <span
                    className="self-center text-xl font-semibold whitespace-nowrap
                   dark:text-white"
                  >
                    Delta Executor
                  </span>
                </a>

                <div className="flex items-center lg:order-2">
                  <button
                    data-collapse-toggle="#mobile-menu-2"
                    type="button"
                    className="inline-flex items-center p-2 ml-1 text-sm 
                    rounded-lg lg:hidden focus:outline-none focus:ring-2
                     focus:ring-gray-200"
                    aria-controls="mobile-menu-2"
                    aria-expanded="false"
                  >
                    <span className="sr-only">Open main menu</span>
                    <svg
                      className="w-6 h-6"
                      fill="currentColor"
                      viewBox="0 0 20 20"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        fill-rule="evenodd"
                        d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                        clip-rule="evenodd"
                      ></path>
                    </svg>
                    <svg
                      className="hidden w-6 h-6"
                      fill="currentColor"
                      viewBox="0 0 20 20"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        fill-rule="evenodd"
                        d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                        clip-rule="evenodd"
                      ></path>
                    </svg>
                  </button>
                </div>

                <div
                  className="justify-between items-center w-full lg:flex lg:w-auto lg:order-1"
                  id="mobile-menu-2"
                >
                  <ul className="flex flex-col mt-4 font-medium lg:flex-row lg:space-x-8 lg:mt-0">
                    <li>
                      <a
                        href="key"
                        className="block py-2 pr-4 pl-3 border-b
                         border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent 
                         lg:border-0 lg:hover:text-primary-700 lg:p-0 
                          lg:dark:hover:text-white lg:dark:hover:bg-transparent"
                      >
                        Delta Executor Key
                      </a>
                    </li>
                    <li>
                      <a
                        href="windows"
                        className="block py-2 pr-4 pl-3 border-b
                         border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent 
                         lg:border-0 lg:hover:text-primary-700 lg:p-0 
                          lg:dark:hover:text-white 
                            lg:dark:hover:bg-transparent"
                      >
                        Delta Executor PC
                      </a>
                    </li>
                    <li>
                      <a
                        href="discord_server"
                        className="block py-2 pr-4 pl-3 border-b
                         border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent 
                         lg:border-0 lg:hover:text-primary-700 lg:p-0 
                          lg:dark:hover:text-white lg:dark:hover:bg-transparent"
                      >
                        Discord Server
                      </a>
                    </li>
                    <li>
                      <a
                        href="server_status"
                        className="block py-2 pr-4 pl-3 border-b
                         border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent
                          lg:border-0 lg:hover:text-primary-700 lg:p-0
                           lg:dark:hover:text-white lg:dark:hover:bg-transparent"
                      >
                        Server Status
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </nav>
          </header>

          {children}

          <footer className="bg-white shadow m-0">
            <div
              className="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center 
              md:justify-between"
            >
              <span className="text-sm sm:text-center">
                © 2023{" "}
                <a href="/" className="hover:underline">
                  Delta Executor™
                </a>
                . All Rights Reserved.
                <a href="https://www.dmca.com/Protection/Status.aspx?ID=ca0ed467-dc53-4fb2-bbea-caf54c58a9b4&cdnrdr=1&refurl=https://delta-executor.com/">
                  <img
                    src="https://images.dmca.com/Badges/dmca_protected_sml_120n.png?ID=ca0ed467-dc53-4fb2-bbea-caf54c58a9b4"
                    alt="DMCA.com Protection Status"
                    className="mx-auto"
                  />
                </a>
              </span>

              <ul className="flex flex-wrap items-center mt-3 text-sm font-medium sm:mt-0">
                <li>
                  <a
                    href="/privacy-policy/"
                    className="hover:underline me-4 md:me-6"
                  >
                    Privacy Policy
                  </a>
                </li>
                <li>
                  <a href="/contact-us/" className="hover:underline">
                    Contact
                  </a>
                </li>
              </ul>
            </div>
          </footer>

          {/* <footer>
            <div className="">
              <ul className="flex items-center justify-center p-8 bg-black text-white space-x-80 font-bold">
                <li>
                  <h1>
                    Copyright © 2023 -
                    <a href="#" className="text-blue-600">
                      Delta Executor
                    </a>
                    <span className="px-2">All right reserved.</span>
                    <img
                      src="https://images.dmca.com/Badges/dmca_protected_sml_120n.png?ID=ca0ed467-dc53-4fb2-bbea-caf54c58a9b4"
                      alt="DMCA.com Protection Status"
                      className="px-32"
                    />
                  </h1>
                </li>
                <li>
                  <h1>
                    <a href="/privacy-policy/" className="text-blue-600 px-6">
                      Privacy Policy
                    </a>
                    <a href="/contact-us/" className="text-blue-600">
                      Contact Us
                    </a>
                  </h1>
                </li>
              </ul>
            </div>
          </footer> */}
        </div>
      </body>
    </html>
  );
}
